% Generated by tools/rdf-to-pl.mjs.

% Run with: eyeprolog --goal 'rdf(S, P, O, G)' program.pl.

rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/healthcare-permission'), default_graph).
rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/marketing-prohibition'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('https://example.org/minTrust'), literal('0.80', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/ad-network'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/marketing'), default_graph).
rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/ad-network'), iri('https://example.org/trustScore'), literal('0.28', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/source'), iri('https://example.org/small-clinic'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/recipient'), iri('https://example.org/ad-network'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedPurpose'), iri('https://example.org/marketing'), default_graph).

% Rules
% Source data: examples/input/odrl-dpv-fpv-trust-flow.ttl
% Regenerate with:
% node tools/rdf-to-pl.mjs --rules examples/input/odrl-dpv-fpv-trust-flow-rules.pl examples/input/odrl-dpv-fpv-trust-flow.ttl -o examples/odrl-dpv-fpv-trust-flow.pl
%
% ODRL policy rules, trust scores, and requested flows are RDF data. The rules
% produce one deterministic FPV-style decision report.
%% goal: trust_flow_report(_)

trust_flow_report([Care, Clinic, Ads]) :-
  flow_decision(flow_care, Care),
  flow_decision(flow_clinic, Clinic),
  flow_decision(flow_ads, Ads).

flow_decision(Flow, decision(Flow, permit, confidence(Score), status(executable_flow))) :-
  permitted_flow(Flow, Score).
flow_decision(Flow, decision(Flow, review, confidence(Score), risk(trustworthiness_risk))) :-
  review_flow(Flow, Score).
flow_decision(Flow, decision(Flow, deny, status(blocked_flow), risk(unwanted_disclosure))) :-
  prohibited_flow(Flow).

permitted_flow(Flow, Score) :-
  flow_request(Flow, Source, Recipient, Data, Action, Purpose),
  policy_rule(odrl(permission), Rule, Recipient, Data, Action, Purpose),
  rdf_number(Rule, ex(minTrust), Minimum),
  rdf_number(Source, ex(trustScore), Score),
  Score >= Minimum.

review_flow(Flow, Score) :-
  flow_request(Flow, Source, Recipient, Data, Action, Purpose),
  policy_rule(odrl(permission), Rule, Recipient, Data, Action, Purpose),
  rdf_number(Rule, ex(minTrust), Minimum),
  rdf_number(Source, ex(trustScore), Score),
  Score < Minimum.

prohibited_flow(Flow) :-
  flow_request(Flow, _Source, Recipient, Data, Action, Purpose),
  policy_rule(odrl(prohibition), _Rule, Recipient, Data, Action, Purpose).

flow_request(Flow, Source, Recipient, Data, Action, Purpose) :-
  flow_resource(Flow, Resource),
  rdf_link(Resource, ex(source), Source),
  rdf_link(Resource, ex(recipient), Recipient),
  rdf_link(Resource, ex(data), Data),
  rdf_link(Resource, ex(requestedAction), Action),
  rdf_link(Resource, ex(requestedPurpose), Purpose).

policy_rule(Type, Rule, Recipient, Data, Action, Purpose) :-
  rdf_link(ex('trust-policy'), Type, Rule),
  rdf_link(Rule, odrl(assignee), Recipient),
  rdf_link(Rule, odrl(target), Data),
  rdf_link(Rule, odrl(action), Action),
  rdf_link(Rule, odrl(purpose), Purpose).

flow_resource(flow_care, ex('flow-care')).
flow_resource(flow_clinic, ex('flow-clinic')).
flow_resource(flow_ads, ex('flow-ads')).

rdf_link(Subject, Predicate, Object) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), iri(ObjectIri), default_graph),
  iri_term(Object, ObjectIri).

rdf_number(Subject, Predicate, Number) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), literal(Text, datatype(_Datatype)), default_graph),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

iri_term(ex(Name), Iri) :- namespace_iri('https://example.org/', Name, Iri).
iri_term(odrl(Name), Iri) :- namespace_iri('http://www.w3.org/ns/odrl/2/', Name, Iri).

namespace_iri(Prefix, Name, Iri) :- atom_concat(Prefix, Name, Iri).
