% Generated by tools/rdf-to-pl.mjs.

% Run with: eyeprolog --goal 'rdf(S, P, O, G)' program.pl.

rdf(iri('https://example.org/alice'), iri('https://example.org/claims'), triple(iri('https://example.org/bob'), iri('https://example.org/knows'), iri('https://example.org/carol')), iri('https://example.org/claimsGraph')).

% Rules
% Project a triple term while preserving its named-graph context.
rdf(S, iri('https://example.org/knows'), O, G) :-
  rdf(
    _,
    iri('https://example.org/claims'),
    triple(S, iri('https://example.org/knows'), O),
    G
  ).
%% goal: rdf(X0, X1, X2, X3)
