% Generated by tools/rdf-to-pl.mjs.

% Run with: eyeprolog --goal 'rdf(S, P, O, G)' program.pl.

rdf(iri('https://example.org/alice'), iri('https://example.org/parent'), iri('https://example.org/bob'), iri('https://example.org/family')).
rdf(iri('https://example.org/bob'), iri('https://example.org/parent'), iri('https://example.org/carol'), iri('https://example.org/family')).

% Rules
% Derive relationships inside the named graph that supplied the source data.
rdf(S, iri('https://example.org/ancestor'), O, G) :-
  rdf(S, iri('https://example.org/parent'), O, G).

rdf(S, iri('https://example.org/ancestor'), O, G) :-
  rdf(S, iri('https://example.org/parent'), M, G),
  rdf(M, iri('https://example.org/parent'), O, G).
%% goal: rdf(X0, X1, X2, X3)
